version: '3.1'

services:
  shift:
    build:
      context: .
    ports:
      - "3000:80"
    environment:
      - SECRET_KEY_BASE=some_random_30_char_string
      - DB_BLACKLIST=information_schema,mysql,performance_schema,_pending_drops,common_schema,sys
      - UI_ADMINS=dhanasekar
      - UI_MYSQL_USER=shift
      - UI_MYSQL_PASS=shift
      - UI_LINK=127.0.0.1
      - RUNNER_MYSQL_USER=shift
      - RUNNER_MYSQL_PASS=shift
      - RUNNER_MYSQL_HOST=127.0.0.1
      - RUNNER_MYSQL_PORT=3306
      - SERVER_USER=mydbops
      - SERVER_PASSWORD=DBops474
    healthcheck:
      test: mysqladmin -uroot -proot ping
      interval: 2s
      timeout: 5s
      retries: 30
    container_name: mydbops_shift